tools/gdbsx: fix -Wstringop-truncation warning
gcc-8 complains:

    gx_main.c: In function 'prepare_stop_reply':
    gx_main.c:385:9: error: 'strncpy' output truncated before terminating nul copying 6 bytes from a string of the same length [-Werror=stringop-truncation]
             strncpy(buf, "watch:", 6);
             ^~~~~~~~~~~~~~~~~~~~~~~~~

Since terminating '\0' isn't needed here at all, switch to memcpy.

(cherry picked from commit 7f601f7c341c80d554615556d60e3b8ed1e5ad4f)
Cherry-pick-repository: https://xenbits.xen.org/gitweb/?p=xen.git
Issue: ALB-3594
Signed-off-by: Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>