tools/libxc: fix strncpy size
gcc-8 warns about possible truncation of trailing '\0'.
Final character is overridden by '\0' anyway, so don't bother to copy
it.

This fixes compile failure:

    xc_pm.c: In function 'xc_set_cpufreq_gov':
    xc_pm.c:308:5: error: 'strncpy' specified bound 16 equals destination size [-Werror=stringop-truncation]
         strncpy(scaling_governor, govname, CPUFREQ_NAME_LEN);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

(cherry picked from commit fa7789ef18bd2e716997937af71b2e4b5b00a159)
Cherry-pick-repository: https://xenbits.xen.org/gitweb/?p=xen.git
Issue: ALB-3594
Signed-off-by: Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>