tools/xentop : fix vwprintw -Werror=deprecated-declarations warning
gcc-8.1 complains:

| xentop.c: In function 'print':
| xentop.c:304:4: error: 'vwprintw' is deprecated [-Werror=deprecated-declarations]
|     vwprintw(stdscr, (curses_str_t)fmt, args);
|     ^~~~~~~~

vw_printw is the non-deprecated alternative.

(cherry picked from commit 2b50cdbc444c637575580dcfa6c9525a84d5cc62)
Cherry-pick-repository: https://xenbits.xen.org/gitweb/?p=xen.git
Issue: ALB-3594
Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>