tools/misc: fix hypothetical buffer overflow in xen-lowmemd
gcc-8 complains:

    xen-lowmemd.c: In function 'handle_low_mem':
    xen-lowmemd.c:80:55: error: '%s' directive output may be truncated writing up to 511 bytes into a region of size 489 [-Werror=format-truncation=]
             snprintf(error, BUFSZ,"Failed to write target %s to xenstore", data);
                                                           ^~               ~~~~
    xen-lowmemd.c:80:9: note: 'snprintf' output between 36 and 547 bytes into a destination of size 512
             snprintf(error, BUFSZ,"Failed to write target %s to xenstore", data);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In practice it wouldn't happen, because 'data' contains string
representation of 64-bit unsigned number (20 characters at most).
But place a limit to mute gcc warning.

(cherry picked from commit 27751d89248c8c5eef6d8b56eb8f7d2084145080)
Cherry-pick-repository: https://xenbits.xen.org/gitweb/?p=xen.git
Issue: ALB-3594
Signed-off-by: Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>